
spring:
  application:
    name: boot-demo
  mvc:
    view:
      prefix: /
      suffix: .html
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:mem:greetDb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: '*'
       
